# Generated by Django 2.2.1 on 2019-05-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Products', 'verbose_name_plural': 'Products'},
        ),
    ]
