# Generated by Django 2.2.1 on 2019-05-14 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilestatus',
            options={'verbose_name_plural': 'statuses'},
        ),
    ]
