# Generated by Django 2.2.1 on 2019-05-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotes',
            options={'verbose_name': 'Quotes', 'verbose_name_plural': 'Quotes'},
        ),
    ]
